<?php
require_once 'connection/config.php';
require_once '__init.php';
require_once 'inc/functions.php';
require_once 'inc/Auth.php';
require_once 'inc/AdminDashboard.php';

$pageName = 'dashboard';
$dashboard = mmh_admin_dashboard_data(db(), (string) ($_GET['period'] ?? '7d'), (string) ($_SESSION['admin'] ?? 'Administrator'));
$base = rtrim(mmh_site_public_base_path(), '/');
function mmh_dashboard_escape($value): string { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); }
function mmh_dashboard_relative($time): string { $seconds = max(0, time() - strtotime((string) $time)); if ($seconds < 60) return 'Just now'; if ($seconds < 3600) return floor($seconds / 60) . 'm ago'; if ($seconds < 86400) return floor($seconds / 3600) . 'h ago'; return floor($seconds / 86400) . 'd ago'; }
$maxSeries = max(array_column($dashboard['series'], 'value')) ?: 1;
$dashboardCssPath = __DIR__ . '/../../resources/css/admin-dashboard.css';
$dashboardCssVersion = (string) (is_file($dashboardCssPath) ? (filemtime($dashboardCssPath) ?: 1) : 1);
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Dashboard · <?=mmh_dashboard_escape($dashboard['admin_name'])?></title><?php include 'layouts/admin/header.php'; ?><link rel="stylesheet" href="<?=mmh_site_public_url('resources/css/admin-dashboard.css')?>?v=<?=$dashboardCssVersion?>"></head>
<body class="dash ds-bg-primary admin-operational-dashboard">
<form method="POST" action="<?=$base?>/admin/logout" id="logout-form" class="d-none"><input type="hidden" name="mmh_csrf_token" value="<?=htmlspecialchars(mmh_admin_csrf_token(), ENT_QUOTES, 'UTF-8')?>"></form>
<div class="col-12 d-flex"><?php include 'layouts/admin/aside.php'; ?><div class="main-content in-active admin-dashboard-main"><?php include 'layouts/admin/top-nav.php'; ?>
<main class="admin-dashboard-shell" id="main-content">
  <header class="admin-dashboard-header"><div><p class="admin-dashboard-eyebrow">Operations overview</p><h1>Good <?=date('H') < 12 ? 'morning' : (date('H') < 18 ? 'afternoon' : 'evening')?>, <?=mmh_dashboard_escape(mmh_auth_first_name($dashboard['admin_name'], 'Administrator'))?></h1><p><?=mmh_dashboard_escape($dashboard['period']['label'])?> · <?=date('l, M j, Y')?></p></div><nav class="admin-dashboard-period" aria-label="Dashboard period"><?php foreach(['today'=>'Today','7d'=>'Last 7 days','30d'=>'Last 30 days'] as $key=>$label): ?><a href="<?=$base?>/admin/dashboard?period=<?=$key?>" class="<?=$dashboard['period']['key']===$key?'is-active':''?>"><?=$label?></a><?php endforeach;?></nav></header>

  <?php if ($dashboard['attention']): ?><section class="admin-dashboard-attention" aria-labelledby="attention-title"><header><div><p class="admin-dashboard-eyebrow">Priority work</p><h2 id="attention-title">Needs attention</h2></div><span><?=count($dashboard['attention'])?> item<?=count($dashboard['attention'])===1?'':'s'?></span></header><div class="admin-dashboard-attention-grid"><?php foreach($dashboard['attention'] as $item): ?><a href="<?=$base?>/admin/<?=mmh_dashboard_escape($item['url'])?>"><strong><?=mmh_dashboard_escape($item['count'])?></strong><div><h3><?=mmh_dashboard_escape($item['label'])?></h3><p><?=mmh_dashboard_escape($item['detail'])?></p></div><span class="fas fa-arrow-right" aria-hidden="true"></span></a><?php endforeach;?></div></section><?php else: ?><section class="admin-dashboard-clear"><span class="fas fa-check-circle" aria-hidden="true"></span><div><strong>Everything is up to date.</strong><p>There are no current operational items requiring attention.</p></div></section><?php endif; ?>

  <section class="admin-dashboard-kpis" aria-label="Operational metrics"><?php foreach($dashboard['metrics'] as $metric): ?><a class="admin-dashboard-kpi" href="<?=$base?>/admin/<?=mmh_dashboard_escape($metric['url'])?>"><span class="admin-dashboard-kpi-icon fas <?=mmh_dashboard_escape($metric['icon'])?>" aria-hidden="true"></span><div><p><?=mmh_dashboard_escape($metric['label'])?></p><strong><?=mmh_dashboard_escape($metric['current'])?></strong><?php if ($metric['comparison']): ?><small><?=mmh_dashboard_escape($metric['comparison'])?></small><?php else: ?><small>No change from previous period</small><?php endif;?></div><span class="fas fa-external-link-alt" aria-hidden="true"></span></a><?php endforeach;?></section>

  <section class="admin-dashboard-quick" aria-labelledby="quick-title"><div class="admin-dashboard-section-heading"><div><p class="admin-dashboard-eyebrow">Common tasks</p><h2 id="quick-title">Quick actions</h2></div><a href="<?=$base ?: '/'?>" target="_blank" rel="noopener">View public website <span class="fas fa-external-link-alt" aria-hidden="true"></span></a></div><div class="admin-dashboard-quick-grid"><?php foreach([
    ['courses','fas fa-plus-circle','Add Course'],['courses','fas fa-layer-group','Open Course Content'],['users','fas fa-user-plus','Enroll Student'],['assignments','fas fa-tasks','Create Assignment'],['live-sessions','fas fa-video','Schedule Live Session'],['recovery-plan-templates','fas fa-route','Create Recovery Plan'],['settings','fas fa-cog','Site Settings'],
  ] as [$url,$icon,$label]): ?><a href="<?=$base?>/admin/<?=$url?>"><span class="<?=$icon?>" aria-hidden="true"></span><?=mmh_dashboard_escape($label)?></a><?php endforeach;?></div></section>

  <div class="admin-dashboard-grid">
    <section class="admin-dashboard-card admin-dashboard-activity" aria-labelledby="activity-title"><header class="admin-dashboard-section-heading"><div><p class="admin-dashboard-eyebrow">Student engagement</p><h2 id="activity-title">Active learners by day</h2></div><span><?=mmh_dashboard_escape($dashboard['period']['label'])?></span></header><?php if (array_sum(array_column($dashboard['series'], 'value'))): ?><div class="admin-dashboard-bars" role="img" aria-label="Active learners by day"><div class="admin-dashboard-bars-values"><?php foreach($dashboard['series'] as $point): ?><div><span style="height:<?=max(4, round(($point['value']/$maxSeries)*100))?>%" title="<?=mmh_dashboard_escape($point['label'].': '.$point['value'])?>"></span><small><?=mmh_dashboard_escape($point['label'])?></small></div><?php endforeach;?></div></div><?php else: ?><div class="admin-dashboard-empty"><span class="fas fa-chart-line" aria-hidden="true"></span><p>No student learning activity in this period.</p></div><?php endif;?></section>

    <section class="admin-dashboard-card admin-dashboard-content" aria-labelledby="content-title"><header class="admin-dashboard-section-heading"><div><p class="admin-dashboard-eyebrow">Content operations</p><h2 id="content-title">Publishing status</h2></div><a href="<?=$base?>/admin/courses">Manage content</a></header><dl><?php foreach($dashboard['content'] as $item): ?><div><dt><?=mmh_dashboard_escape($item['label'])?></dt><dd><a href="<?=$base?>/admin/<?=mmh_dashboard_escape($item['url'])?>"><?=mmh_dashboard_escape($item['count'])?></a></dd></div><?php endforeach;?></dl></section>
  </div>

  <div class="admin-dashboard-grid lower">
    <section class="admin-dashboard-card admin-dashboard-recent" aria-labelledby="recent-title"><header class="admin-dashboard-section-heading"><div><p class="admin-dashboard-eyebrow">What happened recently</p><h2 id="recent-title">Recent activity</h2></div></header><?php if($dashboard['activity']): ?><ol><?php foreach($dashboard['activity'] as $activity): ?><li><span class="admin-dashboard-activity-dot" aria-hidden="true"></span><div><strong><?=mmh_dashboard_escape($activity['kind'])?></strong><?php if($activity['subject']!==''): ?><a href="<?=$base?>/admin/<?=mmh_dashboard_escape($activity['url'])?>"><?=mmh_dashboard_escape($activity['subject'])?></a><?php endif;?></div><time datetime="<?=mmh_dashboard_escape($activity['time'])?>"><?=mmh_dashboard_escape(mmh_dashboard_relative($activity['time']))?></time></li><?php endforeach;?></ol><?php else: ?><div class="admin-dashboard-empty"><span class="fas fa-stream" aria-hidden="true"></span><p>No recent administrative or learning activity.</p></div><?php endif;?></section>

    <section class="admin-dashboard-card admin-dashboard-health" aria-labelledby="health-title"><header class="admin-dashboard-section-heading"><div><p class="admin-dashboard-eyebrow">System status</p><h2 id="health-title">Basic health</h2></div><a href="<?=$base?>/admin/settings">Settings</a></header><ul><li class="is-ok"><span class="fas fa-database" aria-hidden="true"></span><div><strong>Database</strong><small>Connected</small></div></li><li class="<?=$dashboard['health']['uploads']?'is-ok':'is-warning'?>"><span class="fas fa-folder-open" aria-hidden="true"></span><div><strong>Site uploads</strong><small><?=$dashboard['health']['uploads']?'Writable':'Needs attention'?></small></div></li><li class="<?=$dashboard['health']['drive']?'is-ok':'is-warning'?>"><span class="fab fa-google-drive" aria-hidden="true"></span><div><strong>Google Drive importer</strong><small><?=$dashboard['health']['drive']?'Configured':'Not configured'?></small></div></li></ul></section>
  </div>

  <section class="admin-dashboard-card admin-dashboard-courses" aria-labelledby="courses-title"><header class="admin-dashboard-section-heading"><div><p class="admin-dashboard-eyebrow">Course operations</p><h2 id="courses-title">Course performance summary</h2></div><a href="<?=$base?>/admin/courses">All courses <span class="fas fa-arrow-right" aria-hidden="true"></span></a></header><div class="table-responsive"><table><thead><tr><th>Course</th><th>Enrolled</th><th>Active</th><th>Pending assignments</th><th>Course State</th><th>Updated</th><th><span class="visually-hidden">Action</span></th></tr></thead><tbody><?php foreach($dashboard['courses'] as $course): ?><tr><td><strong><?=mmh_dashboard_escape($course['course_title'])?></strong></td><td><?=mmh_dashboard_escape($course['enrolled_students'])?></td><td><?=mmh_dashboard_escape($course['active_students'])?></td><td><?=mmh_dashboard_escape($course['pending_assignments'])?></td><td><span class="admin-dashboard-status is-<?=mmh_dashboard_escape($course['course_state'])?>"><?=mmh_dashboard_escape(ucfirst($course['course_state']))?></span></td><td><?=mmh_dashboard_escape(date('M j, Y', strtotime($course['created_at'])))?></td><td><a class="btn btn-outline-secondary btn-sm" href="<?=$base?>/admin/courses">Open</a></td></tr><?php endforeach;?></tbody></table></div></section>
</main>
</div></div>
</body></html>
