<?php
require_once 'connection/config.php';
require_once '__init.php';
require_once 'inc/functions.php';
require_once 'inc/Auth.php';
require_once 'inc/ParentWeeklyReport.php';
require_once 'inc/StudentLearningJourney.php';

$pageName = 'student_learning_journey';
$subPageName = 'student_learning_journey';
$conn = db();
$escape = static fn($value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$base = rtrim((string) $baseUrl, '/');
$courses = mmh_parent_report_courses($conn);
$selectedStudentId = (int) ($_GET['student_id'] ?? 0);
$selectedCourseId = trim((string) ($_GET['course_id'] ?? ''));
if ($selectedCourseId === '' && $selectedStudentId > 0) {
    $stmt = $conn->prepare('SELECT course_id FROM course_logs WHERE user_id = ? ORDER BY purchase_date DESC, id DESC LIMIT 1');
    if ($stmt) { $stmt->bind_param('i', $selectedStudentId); $stmt->execute(); $selectedCourseId = (string) (($stmt->get_result()->fetch_assoc()['course_id'] ?? '') ?: ''); $stmt->close(); }
}
if ($selectedCourseId === '') { $selectedCourseId = (string) ($courses[0]['course_id'] ?? ''); }
$students = $selectedCourseId !== '' ? mmh_parent_report_students($conn, $selectedCourseId) : [];
if ($selectedStudentId <= 0 && $students) { $selectedStudentId = (int) $students[0]['user_id']; }
$journey = ($selectedCourseId !== '' && $selectedStudentId > 0) ? mmh_learning_journey_resolve($conn, $selectedStudentId, $selectedCourseId) : ['sections' => [], 'total' => 0, 'completed' => 0, 'percentage' => null];
$flash = $_SESSION['learning_journey_flash'] ?? null;
unset($_SESSION['learning_journey_flash']);
$index = 0;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Manage Learning Journey | <?= $escape($site_name ?? 'Math Mastery Hub') ?></title>
<?php include 'layouts/admin/header.php'; ?>
<style>
.journey-admin{margin-top:55px;padding:24px;max-width:1180px}.journey-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-lg);box-shadow:var(--shadow-sm);padding:20px;margin-bottom:18px}.journey-toolbar{display:flex;gap:12px;align-items:end;flex-wrap:wrap}.journey-toolbar label{display:grid;gap:6px;min-width:220px;color:var(--text-muted);font-size:.78rem;font-weight:700}.journey-section{border:1px solid var(--border);border-radius:var(--radius-md);margin:0 0 12px;overflow:hidden}.journey-section>summary{cursor:pointer;padding:15px 17px;background:var(--surface-hover);font-weight:750;color:var(--text-primary);list-style:none}.journey-section>summary::-webkit-details-marker{display:none}.journey-section-body{padding:6px 17px 12px}.journey-row{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:11px 0;border-top:1px solid var(--border)}.journey-row:first-child{border-top:0}.journey-row-label{display:flex;align-items:center;gap:9px;color:var(--text-primary)}.journey-row-meta{display:block;color:var(--text-muted);font-size:.76rem;margin-top:2px}.journey-row-actions{display:flex;align-items:center;gap:8px;color:var(--text-muted);font-size:.78rem}.journey-source{font-size:.72rem;color:var(--primary)}.journey-help{color:var(--text-muted);line-height:1.55;font-size:.86rem}.journey-save{position:sticky;bottom:12px;display:flex;justify-content:flex-end;padding-top:10px}.journey-progress{font-size:.88rem;color:var(--text-secondary)}@media(max-width:650px){.journey-admin{padding:14px}.journey-row{align-items:flex-start}.journey-row-actions{flex-direction:column;align-items:flex-end}.journey-toolbar label{min-width:100%}}
</style></head><body class="dash ds-bg-primary"><div class="col-12 d-flex"><?php include 'layouts/admin/aside.php'; ?><div class="main-content in-active"><?php include 'layouts/admin/top-nav.php'; ?><main class="journey-admin">
<section class="journey-card"><div class="d-flex justify-content-between align-items-start flex-wrap gap-3"><div><div class="course-manager-eyebrow">Student progress</div><h1 class="h3 mb-1">Manage Learning Journey</h1><p class="journey-help mb-0">Tick the real course items the student completed before joining the LMS. Every item remains tied to the published course structure.</p></div><form method="get" class="journey-toolbar" action="<?= $escape($base . '/admin/previous-progress') ?>"><label>Course<select name="course_id" class="form-control form-control-sm" onchange="this.form.submit()"><option value="">Select course</option><?php foreach ($courses as $course): ?><option value="<?= $escape($course['course_id']) ?>" <?= $selectedCourseId === (string) $course['course_id'] ? 'selected' : '' ?>><?= $escape($course['course_title']) ?></option><?php endforeach ?></select></label><?php if ($selectedCourseId !== ''): ?><label>Student<select name="student_id" class="form-control form-control-sm" onchange="this.form.submit()"><option value="">Select student</option><?php foreach ($students as $student): ?><option value="<?= (int) $student['user_id'] ?>" <?= $selectedStudentId === (int) $student['user_id'] ? 'selected' : '' ?>><?= $escape($student['full_name'] ?: $student['username']) ?></option><?php endforeach ?></select></label><?php endif; ?></form></div></section>
<?php if (is_array($flash)): ?><div class="alert alert-<?= !empty($flash['ok']) ? 'success' : 'danger' ?>"><?= $escape($flash['message'] ?? '') ?></div><?php endif; ?>
<?php if (!$selectedCourseId || !$selectedStudentId): ?><section class="journey-card"><p class="journey-help mb-0">Choose a course and student to view the Learning Journey.</p></section>
<?php elseif (!$journey['sections']): ?><section class="journey-card"><p class="journey-help mb-0">This course has no published trackable items yet.</p></section>
<?php else: ?><form method="post" action="<?= $escape($base . '/admin/requests/previous-progress/save') ?>"><input type="hidden" name="_token" value="<?= $escape(mmh_auth_csrf_token()) ?>"><input type="hidden" name="course_id" value="<?= $escape($selectedCourseId) ?>"><input type="hidden" name="student_id" value="<?= (int) $selectedStudentId ?>"><section class="journey-card"><div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h2 class="h5 mb-0">Learning Journey</h2><span class="journey-help">Historical evidence is saved with its source and administrator.</span></div><div class="journey-toolbar"><label>Evidence source<select name="source" class="form-control form-control-sm"><option value="manual">Manual</option><option value="whatsapp">WhatsApp</option></select></label><span class="journey-progress"><?= (int) $journey['completed'] ?> of <?= (int) $journey['total'] ?> items completed</span></div></div>
<?php foreach ($journey['sections'] as $section): ?><details class="journey-section" open><summary><?= $escape($section['title'] ?: 'General') ?></summary><div class="journey-section-body">
<?php foreach ($section['items'] as $item): $kind = (string) $item['item_kind']; $label = $kind === 'homework' ? 'Homework' : ($kind === 'recording' ? 'Recording' : 'Lesson'); $checked = !empty($item['is_completed']); ?><div class="journey-row"><div class="journey-row-label"><span class="fas <?= $kind === 'homework' ? 'fa-clipboard-check' : ($kind === 'recording' ? 'fa-play-circle' : 'fa-book-open') ?>" aria-hidden="true"></span><span><strong><?= $escape($item['item_title']) ?></strong><span class="journey-row-meta"><?= $escape($label) ?> · Item <?= $escape($item['item_id']) ?><?php if (!empty($item['assignment_id'])): ?> · Assignment <?= $escape($item['assignment_id']) ?><?php endif; ?></span></span></div><div class="journey-row-actions"><span class="journey-source"><?= $escape($item['evidence_source'] ?: 'Not recorded') ?></span><input type="hidden" name="journey[<?= $index ?>][item_kind]" value="<?= $escape($kind) ?>"><input type="hidden" name="journey[<?= $index ?>][section_id]" value="<?= $escape($section['section_id'] === '__general__' ? '' : $section['section_id']) ?>"><input type="hidden" name="journey[<?= $index ?>][item_id]" value="<?= $escape($item['item_id']) ?>"><input type="hidden" name="journey[<?= $index ?>][assignment_id]" value="<?= $escape($item['assignment_id']) ?>"><input type="hidden" name="journey[<?= $index ?>][completed]" value="0"><input type="checkbox" name="journey[<?= $index ?>][completed]" value="1" <?= $checked ? 'checked' : '' ?> aria-label="Mark <?= $escape($item['item_title']) ?> complete"></div></div><?php $index++; endforeach; ?>
<?php foreach ($section['live_sessions'] as $session): $checked = !empty($session['is_completed']); ?><div class="journey-row"><div class="journey-row-label"><span class="fas fa-user-check" aria-hidden="true"></span><span><strong>Live attendance</strong><span class="journey-row-meta"><?= $escape($session['scheduled_start_at']) ?> · Occurrence <?= $escape($session['occurrence_id']) ?></span></span></div><div class="journey-row-actions"><span class="journey-source"><?= $escape($session['evidence_source'] ?: 'Not recorded') ?></span><input type="hidden" name="journey[<?= $index ?>][item_kind]" value="live_session"><input type="hidden" name="journey[<?= $index ?>][section_id]" value="<?= $escape($section['section_id']) ?>"><input type="hidden" name="journey[<?= $index ?>][occurrence_id]" value="<?= $escape($session['occurrence_id']) ?>"><input type="hidden" name="journey[<?= $index ?>][completed]" value="0"><input type="checkbox" name="journey[<?= $index ?>][completed]" value="1" <?= $checked ? 'checked' : '' ?> aria-label="Mark live attendance complete"></div></div><?php $index++; endforeach; ?></div></details><?php endforeach; ?><div class="journey-save"><button class="btn btn-primary" type="submit">Save Learning Journey</button></div></section></form><?php endif; ?>
</main></div></div></body></html>
