<?php
require_once 'connection/config.php';
require_once '__init.php';
require_once 'inc/functions.php';
require_once 'inc/Auth.php';
require_once 'inc/ParentWeeklyReport.php';
require_once 'inc/RecoveryPlan.php';

$pageName = 'student_learning_journey';
$subPageName = 'recovery_plan';
$conn = db();
$escape = static fn($value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$base = rtrim((string) $baseUrl, '/');
$selectedStudentId = (int) ($_GET['student_id'] ?? 0);
$selectedCourseId = trim((string) ($_GET['course_id'] ?? ''));
$selectedPlanId = (int) ($_GET['plan_id'] ?? 0);
$courses = mmh_parent_report_courses($conn);
if ($selectedCourseId === '' && $selectedStudentId > 0) {
    $stmt = $conn->prepare('SELECT course_id FROM course_logs WHERE user_id = ? ORDER BY purchase_date DESC, id DESC LIMIT 1');
    if ($stmt) { $stmt->bind_param('i', $selectedStudentId); $stmt->execute(); $selectedCourseId = (string) (($stmt->get_result()->fetch_assoc()['course_id'] ?? '') ?: ''); $stmt->close(); }
}
if ($selectedCourseId === '') $selectedCourseId = (string) ($courses[0]['course_id'] ?? '');
$students = $selectedCourseId !== '' ? mmh_parent_report_students($conn, $selectedCourseId) : [];
if ($selectedStudentId <= 0 && $students) $selectedStudentId = (int) $students[0]['user_id'];
$availableItems = $selectedCourseId !== '' ? mmh_learning_journey_visible_items($conn, $selectedCourseId) : [];
$plans = ($selectedCourseId !== '' && $selectedStudentId > 0) ? mmh_recovery_plan_statuses($conn, $selectedStudentId, $selectedCourseId) : [];
if ($selectedPlanId <= 0) foreach ($plans as $candidate) { if (in_array((string) $candidate['status'], ['active', 'draft'], true)) { $selectedPlanId = (int) $candidate['id']; break; } }
$plan = ($selectedCourseId !== '' && $selectedStudentId > 0 && $selectedPlanId > 0) ? mmh_recovery_plan_load($conn, $selectedStudentId, $selectedCourseId, $selectedPlanId) : null;
if ($plan) $plan = mmh_recovery_plan_sync($conn, $plan, $selectedStudentId, $selectedCourseId);
$flash = $_SESSION['recovery_plan_flash'] ?? null;
unset($_SESSION['recovery_plan_flash']);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Recovery Plan | <?= $escape($site_name ?? 'Math Mastery Hub') ?></title>
<?php include 'layouts/admin/header.php'; ?>
<style>
.recovery-admin{max-width:1220px;margin-top:55px;padding:24px}.recovery-card{padding:20px;margin-bottom:16px;border:1px solid var(--border);border-radius:var(--radius-lg);background:var(--surface);box-shadow:var(--shadow-sm)}.recovery-toolbar,.recovery-actions{display:flex;align-items:end;gap:10px;flex-wrap:wrap}.recovery-toolbar label{display:grid;gap:6px;min-width:210px;color:var(--text-muted);font-size:.78rem;font-weight:700}.recovery-help{color:var(--text-muted);font-size:.86rem;line-height:1.55}.recovery-header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;flex-wrap:wrap}.recovery-rows{display:grid;gap:10px;margin-top:16px}.recovery-row{display:grid;grid-template-columns:28px minmax(220px,1.8fr) 120px 100px 42px;gap:8px;align-items:start;padding:12px;border:1px solid var(--border);border-radius:var(--radius-md);background:var(--surface-elevated)}.recovery-row textarea{grid-column:2/-1}.recovery-row-options{grid-column:2/-1;display:flex;gap:14px;flex-wrap:wrap;color:var(--text-secondary);font-size:.76rem}.recovery-row-index{padding-top:8px;color:var(--text-muted);font-weight:800;text-align:center}.recovery-row-actions{display:flex;flex-direction:column;gap:4px}.recovery-row-actions button{padding:3px 7px;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--surface);color:var(--text-muted)}.recovery-status{display:inline-flex;padding:5px 9px;border-radius:999px;background:var(--surface-hover);font-size:.75rem;font-weight:800}.recovery-status.active{color:var(--success)}.recovery-status.completed{color:var(--secondary)}.recovery-status.draft{color:var(--warning)}@media(max-width:760px){.recovery-admin{padding:14px}.recovery-row{grid-template-columns:26px minmax(0,1fr) 38px}.recovery-row:nth-child(n)>:nth-child(3),.recovery-row:nth-child(n)>:nth-child(4),.recovery-row-options,.recovery-row textarea{grid-column:2}.recovery-row-actions{grid-column:3;grid-row:1}}
</style></head><body class="dash ds-bg-primary"><div class="col-12 d-flex"><?php include 'layouts/admin/aside.php'; ?><div class="main-content in-active"><?php include 'layouts/admin/top-nav.php'; ?><main class="recovery-admin">
<section class="recovery-card"><div class="recovery-header"><div><div class="course-manager-eyebrow">Student support</div><h1 class="h3 mb-1">Recovery Plan</h1><p class="recovery-help mb-0">Select existing published course items. Completion comes from Learning Journey and never changes LMS history.</p></div><form method="get" class="recovery-toolbar" action="<?= $escape($base . '/admin/recovery-plan') ?>"><label>Course<select name="course_id" class="form-control form-control-sm" onchange="this.form.submit()"><option value="">Select course</option><?php foreach ($courses as $course): ?><option value="<?= $escape($course['course_id']) ?>" <?= $selectedCourseId === (string) $course['course_id'] ? 'selected' : '' ?>><?= $escape($course['course_title']) ?></option><?php endforeach; ?></select></label><?php if ($selectedCourseId !== ''): ?><label>Student<select name="student_id" class="form-control form-control-sm" onchange="this.form.submit()"><option value="">Select student</option><?php foreach ($students as $student): ?><option value="<?= (int) $student['user_id'] ?>" <?= $selectedStudentId === (int) $student['user_id'] ? 'selected' : '' ?>><?= $escape($student['full_name'] ?: $student['username']) ?></option><?php endforeach; ?></select></label><?php endif; ?></form></div></section>
<?php if (is_array($flash)): ?><div class="alert alert-<?= !empty($flash['ok']) ? 'success' : 'danger' ?>"><?= $escape($flash['message'] ?? '') ?></div><?php endif; ?>
<?php if (!$selectedCourseId || !$selectedStudentId): ?><section class="recovery-card"><p class="recovery-help mb-0">Choose an enrolled course and student to manage a plan.</p></section>
<?php else: ?>
<section class="recovery-card"><div class="recovery-header"><div><h2 class="h5 mb-1">Plans for this student</h2><p class="recovery-help mb-0">Only one plan can be active. Drafts can be edited before activation.</p></div><div class="recovery-actions"><form method="post" action="<?= $escape($base . '/admin/requests/recovery-plan/save') ?>"><input type="hidden" name="_token" value="<?= $escape(mmh_auth_csrf_token()) ?>"><input type="hidden" name="course_id" value="<?= $escape($selectedCourseId) ?>"><input type="hidden" name="student_id" value="<?= (int) $selectedStudentId ?>"><input type="hidden" name="action" value="create"><button class="btn btn-primary btn-sm" type="submit">Create Recovery Plan</button></form><?php if ($plans): ?><label class="recovery-toolbar"><select class="form-control form-control-sm" aria-label="Select plan" onchange="if(this.value) window.location=this.value"><option value="">Select plan</option><?php foreach ($plans as $candidate): ?><option value="<?= $escape($base . '/admin/recovery-plan?course_id=' . rawurlencode($selectedCourseId) . '&student_id=' . (int) $selectedStudentId . '&plan_id=' . (int) $candidate['id']) ?>" <?= $selectedPlanId === (int) $candidate['id'] ? 'selected' : '' ?>><?= $escape($candidate['title']) ?> · <?= $escape(ucfirst($candidate['status'])) ?></option><?php endforeach; ?></select></label><?php endif; ?></div></div></section>
<?php if (!$plan): ?><section class="recovery-card"><p class="recovery-help mb-0">Create a plan to start selecting existing course items.</p></section>
<?php else: ?><form method="post" action="<?= $escape($base . '/admin/requests/recovery-plan/save') ?>"><input type="hidden" name="_token" value="<?= $escape(mmh_auth_csrf_token()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="course_id" value="<?= $escape($selectedCourseId) ?>"><input type="hidden" name="student_id" value="<?= (int) $selectedStudentId ?>"><input type="hidden" name="plan_id" value="<?= (int) $plan['id'] ?>"><section class="recovery-card"><div class="recovery-header"><div><input class="form-control mb-2" name="title" value="<?= $escape($plan['title']) ?>" maxlength="180" aria-label="Recovery Plan title"><span class="recovery-status <?= $escape($plan['status']) ?>"><?= $escape(ucfirst($plan['status'])) ?></span><span class="ms-2"><?= (int) ($plan['required_completed'] ?? 0) ?> / <?= (int) ($plan['required_total'] ?? 0) ?> required complete</span></div><button class="btn btn-primary" type="submit">Save plan</button></div><div class="recovery-rows" id="recovery-rows">
<?php foreach (($plan['items'] ?? []) as $index => $item): ?><div class="recovery-row" data-recovery-row><span class="recovery-row-index" data-index><?= $index + 1 ?></span><select class="form-control form-control-sm" name="items[<?= $index ?>][item_id]" aria-label="Recovery item <?= $index + 1 ?>"><?php foreach ($availableItems as $available): ?><option value="<?= $escape($available['item_id']) ?>" <?= (string) $available['item_id'] === (string) $item['item_id'] ? 'selected' : '' ?>><?= $escape($available['item_title']) ?> · <?= $escape(mmh_recovery_plan_item_label($available)) ?></option><?php endforeach; ?></select><input class="form-control form-control-sm" type="number" name="items[<?= $index ?>][estimated_duration]" min="0" max="1440" value="<?= $item['estimated_duration'] === null ? '' : (int) $item['estimated_duration'] ?>" placeholder="Minutes" aria-label="Estimated duration"><input class="form-control form-control-sm" type="number" name="items[<?= $index ?>][weight]" min="0" step="0.01" value="<?= $item['weight'] === null ? '' : $escape($item['weight']) ?>" placeholder="Weight" aria-label="Weight"><div class="recovery-row-options"><label><input type="hidden" name="items[<?= $index ?>][required]" value="0"><input type="checkbox" name="items[<?= $index ?>][required]" value="1" <?= !empty($item['is_required']) ? 'checked' : '' ?>> Required</label><label><input type="hidden" name="items[<?= $index ?>][locked_until_previous]" value="0"><input type="checkbox" name="items[<?= $index ?>][locked_until_previous]" value="1" <?= !empty($item['locked_until_previous']) ? 'checked' : '' ?>> Lock until previous complete</label><span><?= $escape($item['section_title'] ?: 'General') ?> · <?= $escape(mmh_recovery_plan_item_label($item)) ?></span></div><textarea class="form-control form-control-sm" name="items[<?= $index ?>][teacher_note]" maxlength="1000" placeholder="Teacher note (optional)"><?= $escape($item['teacher_note']) ?></textarea><div class="recovery-row-actions"><button type="button" data-move="up" aria-label="Move item up">↑</button><button type="button" data-move="down" aria-label="Move item down">↓</button><button type="button" data-remove-row aria-label="Remove item">×</button></div></div><?php endforeach; ?></div><div class="recovery-actions mt-3"><select id="recovery-picker" class="form-control form-control-sm" aria-label="Add existing course item"><option value="">Choose existing item</option><?php foreach ($availableItems as $available): ?><option value="<?= $escape($available['item_id']) ?>"><?= $escape($available['item_title']) ?> · <?= $escape(mmh_recovery_plan_item_label($available)) ?></option><?php endforeach; ?></select><button class="btn btn-outline-secondary btn-sm" type="button" id="recovery-add">Add item</button></div></section></form>
<div class="recovery-actions mb-4"><form method="post" action="<?= $escape($base . '/admin/requests/recovery-plan/save') ?>"><input type="hidden" name="_token" value="<?= $escape(mmh_auth_csrf_token()) ?>"><input type="hidden" name="action" value="duplicate"><input type="hidden" name="course_id" value="<?= $escape($selectedCourseId) ?>"><input type="hidden" name="student_id" value="<?= (int) $selectedStudentId ?>"><input type="hidden" name="plan_id" value="<?= (int) $plan['id'] ?>"><button class="btn btn-outline-secondary btn-sm" type="submit">Duplicate as draft</button></form><?php if (($plan['status'] ?? '') === 'draft' || ($plan['status'] ?? '') === 'completed'): ?><form method="post" action="<?= $escape($base . '/admin/requests/recovery-plan/save') ?>"><input type="hidden" name="_token" value="<?= $escape(mmh_auth_csrf_token()) ?>"><input type="hidden" name="action" value="<?= $plan['status'] === 'draft' ? 'activate' : 'reopen' ?>"><input type="hidden" name="course_id" value="<?= $escape($selectedCourseId) ?>"><input type="hidden" name="student_id" value="<?= (int) $selectedStudentId ?>"><input type="hidden" name="plan_id" value="<?= (int) $plan['id'] ?>"><button class="btn btn-success btn-sm" type="submit"><?= $plan['status'] === 'draft' ? 'Activate plan' : 'Reopen plan' ?></button></form><?php endif; ?><form method="post" action="<?= $escape($base . '/admin/requests/recovery-plan/save') ?>"><input type="hidden" name="_token" value="<?= $escape(mmh_auth_csrf_token()) ?>"><input type="hidden" name="action" value="archive"><input type="hidden" name="course_id" value="<?= $escape($selectedCourseId) ?>"><input type="hidden" name="student_id" value="<?= (int) $selectedStudentId ?>"><input type="hidden" name="plan_id" value="<?= (int) $plan['id'] ?>"><button class="btn btn-outline-danger btn-sm" type="submit">Archive plan</button></form></div>
<?php endif; ?><?php endif; ?>
</main></div></div>
<template id="recovery-template"><div class="recovery-row" data-recovery-row><span class="recovery-row-index" data-index></span><select class="form-control form-control-sm" name="items[__INDEX__][item_id]" aria-label="Recovery item"><option value="">Choose existing item</option><?php foreach ($availableItems as $available): ?><option value="<?= $escape($available['item_id']) ?>"><?= $escape($available['item_title']) ?> · <?= $escape(mmh_recovery_plan_item_label($available)) ?></option><?php endforeach; ?></select><input class="form-control form-control-sm" type="number" name="items[__INDEX__][estimated_duration]" min="0" max="1440" placeholder="Minutes" aria-label="Estimated duration"><input class="form-control form-control-sm" type="number" name="items[__INDEX__][weight]" min="0" step="0.01" placeholder="Weight" aria-label="Weight"><div class="recovery-row-options"><label><input type="hidden" name="items[__INDEX__][required]" value="0"><input type="checkbox" name="items[__INDEX__][required]" value="1" checked> Required</label><label><input type="hidden" name="items[__INDEX__][locked_until_previous]" value="0"><input type="checkbox" name="items[__INDEX__][locked_until_previous]" value="1"> Lock until previous complete</label></div><textarea class="form-control form-control-sm" name="items[__INDEX__][teacher_note]" maxlength="1000" placeholder="Teacher note (optional)"></textarea><div class="recovery-row-actions"><button type="button" data-move="up" aria-label="Move item up">↑</button><button type="button" data-move="down" aria-label="Move item down">↓</button><button type="button" data-remove-row aria-label="Remove item">×</button></div></div></template>
<script>
(function(){const list=document.getElementById('recovery-rows'),picker=document.getElementById('recovery-picker'),add=document.getElementById('recovery-add'),template=document.getElementById('recovery-template');if(!list||!picker||!add||!template)return;function renumber(){Array.from(list.querySelectorAll('[data-recovery-row]')).forEach(function(row,index){row.querySelector('[data-index]').textContent=index+1;row.querySelectorAll('[name]').forEach(function(input){input.name=input.name.replace(/items\[[^\]]+\]/,'items['+index+']');});});}add.addEventListener('click',function(){if(!picker.value)return;const fragment=template.content.cloneNode(true);const row=fragment.querySelector('[data-recovery-row]');row.querySelector('select').value=picker.value;list.appendChild(fragment);picker.value='';renumber();});list.addEventListener('click',function(event){const button=event.target.closest('button');if(!button)return;const row=button.closest('[data-recovery-row]');if(button.hasAttribute('data-remove-row')){row.remove();renumber();return;}const sibling=button.getAttribute('data-move')==='up'?row.previousElementSibling:row.nextElementSibling;if(sibling){if(button.getAttribute('data-move')==='up')list.insertBefore(row,sibling);else list.insertBefore(sibling,row);renumber();}});renumber();})();
</script></body></html>
